# Generated by Django 4.1 on 2022-08-15 06:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200, null=True)),
                ('action_type', models.CharField(choices=[('view', 'Get'), ('create', 'Post'), ('update', 'Patch'), ('delete', 'Delete')], max_length=16)),
                ('action_detail', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('social_account_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=30, null=True)),
                ('memo', models.CharField(max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EpinephrineRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 8, 15, 15, 27, 29, 653335))),
                ('result_rate', models.FloatField(max_length=250)),
                ('dose', models.FloatField(max_length=250)),
                ('weight', models.FloatField(max_length=250)),
                ('drug', models.FloatField(max_length=250)),
                ('afterSuffleIV', models.FloatField(max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
