# Generated by Django 4.1 on 2022-08-15 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epinephrinerate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 15, 27, 50, 568842)),
        ),
    ]
